<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121218090330 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE witte_kanban_domain_model_ticket ADD file VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE witte_kanban_domain_model_ticket ADD CONSTRAINT FK_927A49B38C9F3610 FOREIGN KEY (file) REFERENCES typo3_flow_resource_resource (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_927A49B38C9F3610 ON witte_kanban_domain_model_ticket (file)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE witte_kanban_domain_model_ticket DROP FOREIGN KEY FK_927A49B38C9F3610");
		$this->addSql("DROP INDEX IDX_927A49B38C9F3610 ON witte_kanban_domain_model_ticket");
		$this->addSql("ALTER TABLE witte_kanban_domain_model_ticket DROP file");
	}
}

?>