<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121101211844 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE witte_kanban_domain_model_board (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, created DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE witte_kanban_domain_model_column (persistence_object_identifier VARCHAR(40) NOT NULL, board VARCHAR(40) DEFAULT NULL, parentcolumn VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, sort INT NOT NULL, created DATETIME NOT NULL, limitvalue INT NOT NULL, INDEX IDX_7889636E58562B47 (board), INDEX IDX_7889636E3B5AFF41 (parentcolumn), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE witte_kanban_domain_model_ticket (persistence_object_identifier VARCHAR(40) NOT NULL, slot VARCHAR(40) DEFAULT NULL, board VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, version VARCHAR(255) NOT NULL, created DATETIME NOT NULL, started DATETIME NOT NULL, moved DATETIME NOT NULL, INDEX IDX_927A49B3AC0E2067 (slot), INDEX IDX_927A49B358562B47 (board), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE witte_kanban_domain_model_column ADD CONSTRAINT FK_7889636E58562B47 FOREIGN KEY (board) REFERENCES witte_kanban_domain_model_board (persistence_object_identifier)");
		$this->addSql("ALTER TABLE witte_kanban_domain_model_column ADD CONSTRAINT FK_7889636E3B5AFF41 FOREIGN KEY (parentcolumn) REFERENCES witte_kanban_domain_model_column (persistence_object_identifier)");
		$this->addSql("ALTER TABLE witte_kanban_domain_model_ticket ADD CONSTRAINT FK_927A49B3AC0E2067 FOREIGN KEY (slot) REFERENCES witte_kanban_domain_model_column (persistence_object_identifier)");
		$this->addSql("ALTER TABLE witte_kanban_domain_model_ticket ADD CONSTRAINT FK_927A49B358562B47 FOREIGN KEY (board) REFERENCES witte_kanban_domain_model_board (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE witte_kanban_domain_model_column DROP FOREIGN KEY FK_7889636E58562B47");
		$this->addSql("ALTER TABLE witte_kanban_domain_model_ticket DROP FOREIGN KEY FK_927A49B358562B47");
		$this->addSql("ALTER TABLE witte_kanban_domain_model_column DROP FOREIGN KEY FK_7889636E3B5AFF41");
		$this->addSql("ALTER TABLE witte_kanban_domain_model_ticket DROP FOREIGN KEY FK_927A49B3AC0E2067");
		$this->addSql("DROP TABLE witte_kanban_domain_model_board");
		$this->addSql("DROP TABLE witte_kanban_domain_model_column");
		$this->addSql("DROP TABLE witte_kanban_domain_model_ticket");
	}
}

?>