<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121024224042 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE witte_kanban_domain_model_board (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, created DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE witte_kanban_domain_model_superiorcolumn (persistence_object_identifier VARCHAR(40) NOT NULL, board VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, sort INT NOT NULL, limitvalue INT NOT NULL, created DATETIME NOT NULL, INDEX IDX_A967AFC458562B47 (board), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE witte_kanban_domain_model_subcolumn (persistence_object_identifier VARCHAR(40) NOT NULL, superiorcolumn VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, sort INT NOT NULL, created DATETIME NOT NULL, INDEX IDX_5B1DA10C5976ACD2 (superiorcolumn), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE witte_kanban_domain_model_ticket (persistence_object_identifier VARCHAR(40) NOT NULL, subcolumn VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, created DATETIME NOT NULL, moved DATETIME NOT NULL, INDEX IDX_927A49B31B2F0F5B (subcolumn), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE witte_kanban_domain_model_superiorcolumn ADD CONSTRAINT FK_A967AFC458562B47 FOREIGN KEY (board) REFERENCES witte_kanban_domain_model_board (persistence_object_identifier)");
		$this->addSql("ALTER TABLE witte_kanban_domain_model_subcolumn ADD CONSTRAINT FK_5B1DA10C5976ACD2 FOREIGN KEY (superiorcolumn) REFERENCES witte_kanban_domain_model_superiorcolumn (persistence_object_identifier)");
		$this->addSql("ALTER TABLE witte_kanban_domain_model_ticket ADD CONSTRAINT FK_927A49B31B2F0F5B FOREIGN KEY (subcolumn) REFERENCES witte_kanban_domain_model_subcolumn (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE witte_kanban_domain_model_superiorcolumn DROP FOREIGN KEY FK_A967AFC458562B47");
		$this->addSql("ALTER TABLE witte_kanban_domain_model_subcolumn DROP FOREIGN KEY FK_5B1DA10C5976ACD2");
		$this->addSql("ALTER TABLE witte_kanban_domain_model_ticket DROP FOREIGN KEY FK_927A49B31B2F0F5B");
		$this->addSql("DROP TABLE witte_kanban_domain_model_board");
		$this->addSql("DROP TABLE witte_kanban_domain_model_superiorcolumn");
		$this->addSql("DROP TABLE witte_kanban_domain_model_subcolumn");
		$this->addSql("DROP TABLE witte_kanban_domain_model_ticket");
	}
}

?>