-
  name: 'Witte Kanban Application'
  uriPattern: ''
  defaults:
    '@package':    'Witte.Kanban'
    '@controller': 'Base'
    '@action':     'index'
-
  name: 'Witte Kanban Application'
  uriPattern: '/{@controller}/{@action}'
  defaults:
    '@package':    'Witte.Kanban'